[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0
pidfile=/tmp/supervisord.pid

[program:redis]
command=redis-server --port 6379 --daemonize no --dir /tmp
autostart=true
autorestart=true
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0

[program:backend]
command=npm run start --workspace=backend
directory=/app
autostart=true
autorestart=true
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
environment=PORT="7860",REDIS_URL="redis://127.0.0.1:6379",REDIS_HOST="127.0.0.1",REDIS_PORT="6379",NODE_ENV="production",NODE_OPTIONS="--max-old-space-size=1536"
