import { Request, Response, Router } from 'express';
import { requireAuth } from '../middlewares/auth.middleware';
import { createClient } from '@supabase/supabase-js';
import sharp from 'sharp';
import { TOKEN_COSTS } from '../config/tokenCosts';
import { applyCreditMutation } from '../services/creditLedger.service';

// 🟢 RAM PROTECTOR: Disable Sharp's internal memory cache & limit threads.
// এটি না করলে 1GB RAM এর সার্ভারে 3-4 টা ইমেজ রেন্ডার হলেই সার্ভার ক্র্যাশ করবে।
sharp.cache(false);
sharp.concurrency(1);

const supabase = createClient(
  process.env.SUPABASE_URL || '',
  process.env.SUPABASE_SERVICE_ROLE_KEY || ''
);

export async function generateWallpaperHandler(req: Request, res: Response): Promise<void> {
  try {
    const userId = (req as any).user?.id;
    const { topic, formulas, theme = 'minimalist', language } = req.body;

    if (!userId || !topic || !formulas || !Array.isArray(formulas)) {
      res.status(400).json({ error: 'Missing topic or formulas array' });
      return;
    }

    const tier = (req as any).user?.tier || 'Free';

    // 🟢 1.5. TOKEN VERIFICATION & DEDUCTION (IDOR Protected)
    const cost = TOKEN_COSTS.WALLPAPER_GEN;
    if (tier.toLowerCase() !== 'pro') {
      const { data: userProfile, error: profileErr } = await supabase.from('profiles').select('tokens').eq('id', userId).single();
      
      if (profileErr || !userProfile || userProfile.tokens < cost) {
        res.status(402).json({ error: 'INSUFFICIENT_TOKENS', required: cost });
        return;
      }
      
      
    }

    // 🟢 Theme Colors & Styles (Cyberpunk, Minimalist, Aesthetic)
    let bgColor = '#090d16'; // Deep space dark
    let titleColor = '#38bdf8'; // Sky blue
    let textColor = '#f8fafc'; // Crisp white
    let accentColor = '#818cf8'; // Indigo accent

    if (theme === 'cyberpunk') {
      bgColor = '#030712';
      titleColor = '#06b6d4'; // Neon Cyan
      textColor = '#f43f5e'; // Neon Pink
      accentColor = '#eab308'; // Neon Yellow
    } else if (theme === 'aesthetic') {
      bgColor = '#1e1b4b'; // Deep Indigo/Medical
      titleColor = '#a78bfa'; // Soft Purple
      textColor = '#e2e8f0'; 
      accentColor = '#f472b6'; // Rose
    }

    // 🟢 Generate Dynamic SVG Layout for 1080x1920 (Standard HD Mobile Wallpaper)
    const width = 1080;
    const height = 1920;

    let svgContent = `
      <svg width="${width}" height="${height}" viewBox="0 0 ${width} ${height}" xmlns="http://www.w3.org/2000/svg">
        <style>
          .title { font-family: 'sans-serif'; font-size: 54px; font-weight: 900; fill: ${titleColor}; text-transform: uppercase; letter-spacing: 2px; }
          .subtitle { font-family: 'sans-serif'; font-size: 28px; font-weight: bold; fill: ${accentColor}; opacity: 0.8; }
          .formula { font-family: 'monospace'; font-size: 38px; font-weight: bold; fill: ${textColor}; }
          .watermark { font-family: 'sans-serif'; font-size: 24px; font-weight: bold; fill: ${accentColor}; opacity: 0.3; letter-spacing: 4px; }
          .card { fill: ${bgColor}; stroke: ${accentColor}; stroke-width: 2; opacity: 0.15; }
        </style>
        
        <rect width="100%" height="100%" fill="${bgColor}"/>
        
        <rect x="50" y="50" width="${width - 100}" height="${height - 100}" fill="none" stroke="${accentColor}" stroke-width="3" opacity="0.2" rx="30"/>
        <rect x="80" y="240" width="${width - 160}" height="${height - 400}" class="card" rx="20"/>

        <text x="120" y="140" class="title">${topic.substring(0, 25)}</text>
        <text x="120" y="190" class="subtitle">EXAM-NIGHT REVISION WALLPAPER</text>
        
        `;

    // Injecting formulas sequentially into the SVG Canvas layout safely
    let currentY = 320;
    formulas.slice(0, 15).forEach((item: string, index: number) => {
      // Stripping potential raw latex triggers for clean mobile canvas display
      const cleanText = item.replace(/\$/g, '').trim();
      svgContent += `
        <circle cx="130" cy="${currentY - 12}" r="6" fill="${accentColor}" />
        <text x="160" y="${currentY}" class="formula">${cleanText.substring(0, 42)}</text>
      `;
      currentY += 90; // Line spacing
    });

    // Brand Watermark
    svgContent += `
        <text x="${width / 2}" y="${height - 100}" text-anchor="middle" class="watermark">GENERATED BY Prepia</text>
      </svg>
    `;

    // 🟢 Step 4: High-Performance Processing via Sharp (Milli-seconds latency)
    const imageBuffer = await sharp(Buffer.from(svgContent))
      .png()
      .toBuffer();

    // 🟢 Background Async Save to Supabase History (Zero-Cost for future lookups)
    void supabase.from('wallpaper_history').insert([{
      user_id: userId,
      topic: topic,
      theme: theme,
      formulas_text: JSON.stringify(formulas)
    }]).then((res) => { if (res.error) console.error("Wallpaper DB Save Error:", res.error) });

    // Send high quality stream directly to user's browser download pipeline
    
      // 🟢 DEDUCT TOKENS ONLY ON SUCCESS
      if (tier.toLowerCase() !== 'pro') {
        await applyCreditMutation({ userId, amount: -cost, reason: 'Wallpaper Generator', idempotencyKey: `wallpaper:${userId}:${Date.now()}` });
      }
      
      res.setHeader('Content-Type', 'image/png');
    res.setHeader('Content-Disposition', `attachment; filename="Prepia-${topic.toLowerCase().replace(/\s+/g, '-')}-wallpaper.png"`);
    res.send(imageBuffer);

  } catch (error: any) {
    console.error("🔥 Wallpaper Generation Endpoint Failure:", error.message);
    res.status(500).json({ error: error.message });
  }
}

export function registerWallpaperRoutes(app: any): void {
  const router = Router();
  router.post('/generate', requireAuth, async (req: Request, res: Response) => { await generateWallpaperHandler(req, res); });
  app.use('/api/wallpaper', router);
}
