import re

with open('frontend/src/app/landingTranslations.ts', 'r', encoding='utf-8') as f:
    content = f.read()

# Generate the FAQ string
faqs = [
    {"en_q": "What exactly is Prepia?", "en_a": "Prepia is a next-generation, context-aware AI built specifically for students. It uses RAG (Retrieval-Augmented Generation) to read your exact textbooks and syllabuses, answering questions based only on your materials, preventing hallucinations.", "bn_q": "প্রেপিয়া আসলে কী?", "bn_a": "প্রেপিয়া হল শিক্ষার্থীদের জন্য তৈরি একটি নেক্সট-জেনারেশন এআই। এটি RAG ব্যবহার করে আপনার আপলোড করা বই থেকে উত্তর দেয়, যা ভুল তথ্য দেওয়া থেকে বিরত রাখে।", "hi_q": "प्रेपिया वास्तव में क्या है?", "hi_a": "प्रेपिया छात्रों के लिए बनाया गया एक नेक्स्ट-जेनरेशन एआई है। यह RAG का उपयोग करके आपकी अपलोड की गई पुस्तकों से उत्तर देता है, जिससे गलत जानकारी नहीं मिलती।"},
    {"en_q": "How is it different from ChatGPT?", "en_a": "ChatGPT gives generic answers from the internet. Prepia gives hyper-specific answers tailored to your exam syllabus. Plus, we have 28 purpose-built tools (Flashcards, 3D Labs, Concept Battles) that ChatGPT doesn't have.", "bn_q": "এটি চ্যাটজিপিটি থেকে কীভাবে আলাদা?", "bn_a": "চ্যাটজিপিটি ইন্টারনেট থেকে সাধারণ উত্তর দেয়। প্রেপিয়া আপনার পরীক্ষার সিলেবাস অনুযায়ী নির্দিষ্ট উত্তর দেয়। আমাদের রয়েছে ২৮টি বিশেষ টুল যা চ্যাটজিপিটিতে নেই।", "hi_q": "यह चैटजीपीटी से कैसे अलग है?", "hi_a": "चैटजीपीटी इंटरनेट से सामान्य उत्तर देता है। प्रेपिया आपके परीक्षा पाठ्यक्रम के अनुसार विशिष्ट उत्तर देता है। हमारे पास 28 विशेष उपकरण हैं जो चैटजीपीटी में नहीं हैं।"},
    {"en_q": "Why did you build this?", "en_a": "We built Prepia because we saw students wasting hours prompt-engineering generic AIs to get decent study materials. We wanted a one-click 'Magic Button' for every study need.", "bn_q": "আপনারা এটি কেন বানিয়েছেন?", "bn_a": "শিক্ষার্থীদের প্রম্পট লিখতে ঘণ্টার পর ঘণ্টা নষ্ট করতে দেখে আমরা প্রেপিয়া বানিয়েছি। আমরা চাই এক-ক্লিক 'ম্যাজিক বাটন' যা সব পড়াশোনার কাজ করে দেবে।", "hi_q": "आपने इसे क्यों बनाया?", "hi_a": "हमने प्रेपिया बनाया क्योंकि हमने छात्रों को सामान्य एआई को प्रॉम्प्ट करने में घंटों बर्बाद करते देखा। हम हर अध्ययन आवश्यकता के लिए एक 'मैजिक बटन' चाहते थे।"},
    {"en_q": "How do you give services here?", "en_a": "We use a multi-agent architecture powered by OpenAI and Anthropic. You upload a PDF, our OCR engines extract the text, chunk it, embed it via Pinecone, and our controllers route your requests to the cheapest/fastest LLM.", "bn_q": "আপনারা কীভাবে সেবা প্রদান করেন?", "bn_a": "আমরা OpenAI এবং Anthropic এর মাল্টি-এজেন্ট আর্কিটেকচার ব্যবহার করি। আপনি পিডিএফ আপলোড করেন, আমরা সেটি Pinecone এর মাধ্যমে প্রসেস করি এবং দ্রুততম মডেলে রাউট করি।", "hi_q": "आप यहाँ सेवाएँ कैसे देते हैं?", "hi_a": "हम ओपनएआई और एंथ्रोपिक द्वारा संचालित मल्टी-एजेंट आर्किटेक्चर का उपयोग करते हैं। आप पीडीएफ अपलोड करते हैं, हम उसे पाइनकोन के माध्यम से प्रोसेस करते हैं।"},
    {"en_q": "How do tokens work?", "en_a": "You get 500 free tokens on signup. Different tools cost different amounts (e.g., Night Before Exam = 5 tokens). You can buy Pro for 10,000 monthly tokens.", "bn_q": "টোকেন কীভাবে কাজ করে?", "bn_a": "সাইনআপে আপনি ৫০০ ফ্রি টোকেন পাবেন। বিভিন্ন টুলের জন্য আলাদা চার্জ কাটে। বেশি ব্যবহারের জন্য প্রো প্ল্যান নিতে পারেন।", "hi_q": "टोकन कैसे काम करते हैं?", "hi_a": "साइनअप पर आपको 500 मुफ्त टोकन मिलते हैं। विभिन्न उपकरणों के लिए अलग-अलग शुल्क है। अधिक उपयोग के लिए प्रो प्लान लें।"},
    {"en_q": "What happens if I run out of tokens?", "en_a": "You will see our OutOfTokens Modal. You can either wait for your daily free drip (if applicable), invite friends, or upgrade to Pro.", "bn_q": "টোকেন শেষ হয়ে গেলে কী হবে?", "bn_a": "আপনি OutOfTokens মোডাল দেখতে পাবেন। আপনি ডেইলি রিফিলের জন্য অপেক্ষা করতে পারেন, বন্ধুদের ইনভাইট করতে পারেন অথবা প্রো আপগ্রেড করতে পারেন।", "hi_q": "यदि टोकन खत्म हो जाएं तो क्या होगा?", "hi_a": "आप OutOfTokens मोडल देखेंगे। आप दैनिक रिफिल की प्रतीक्षा कर सकते हैं, दोस्तों को आमंत्रित कर सकते हैं या प्रो अपग्रेड कर सकते हैं।"},
    {"en_q": "Is my data secure?", "en_a": "100%. We use Supabase Row Level Security (RLS) and strict IDOR protections. Your uploaded PDFs are private to your account.", "bn_q": "আমার ডাটা কি নিরাপদ?", "bn_a": "১০০%। আমরা Supabase RLS ব্যবহার করি। আপনার আপলোড করা ফাইল সম্পূর্ণ ব্যক্তিগত।", "hi_q": "क्या मेरा डेटा सुरक्षित है?", "hi_a": "100%। हम सुपाबेस RLS का उपयोग करते हैं। आपकी अपलोड की गई फाइलें पूरी तरह से निजी हैं।"},
    {"en_q": "Can teachers use this?", "en_a": "Absolutely. Teachers use Prepia to instantly generate quizzes, syllabus outlines, and grading rubrics from their raw lecture notes.", "bn_q": "শিক্ষকরা কি এটি ব্যবহার করতে পারবেন?", "bn_a": "অবশ্যই। শিক্ষকরা মুহূর্তেই কুইজ ও সিলেবাস আউটলাইন তৈরি করতে পারেন।", "hi_q": "क्या शिक्षक इसका उपयोग कर सकते हैं?", "hi_a": "बिल्कुल। शिक्षक पल भर में क्विज़ और सिलेबस आउटलाइन बना सकते हैं।"},
    {"en_q": "How are guardians benefitted?", "en_a": "Guardians can track their child's progress via the Analytics page and ensure they are studying safely without internet distractions.", "bn_q": "অভিভাবকরা কীভাবে উপকৃত হবেন?", "bn_a": "অ্যানালিটিক্স পেজের মাধ্যমে অভিভাবকরা সন্তানের উন্নতি দেখতে পারেন।", "hi_q": "अभिभावकों को कैसे लाभ होता है?", "hi_a": "एनालिटिक्स पेज के माध्यम से अभिभावक बच्चे की प्रगति को ट्रैक कर सकते हैं।"},
    {"en_q": "What is the Night Before Exam feature?", "en_a": "It's a high-speed panic button. It reads all your uploaded documents simultaneously and gives you a 5-minute condensed cheat sheet of only the most critical topics.", "bn_q": "Night Before Exam ফিচার কী?", "bn_a": "এটি পরীক্ষার আগের রাতের জন্য স্পেশাল ফিচার। এটি দ্রুত সব বই পড়ে গুরুত্বপূর্ণ বিষয়ের চিট-শিট তৈরি করে।", "hi_q": "नाइट बिफोर एग्जाम फीचर क्या है?", "hi_a": "यह परीक्षा से एक रात पहले के लिए विशेष फीचर है। यह महत्वपूर्ण विषयों की चीट शीट बनाता है।"},
    {"en_q": "What is the 3D Molecule Lab?", "en_a": "It visualizes complex chemical structures dynamically in 3D right in your browser, perfect for organic chemistry.", "bn_q": "3D Molecule Lab কী?", "bn_a": "এটি থ্রিডি তে রাসায়নিক গঠন দেখায় যা অরগানিক কেমিস্ট্রির জন্য দারুণ।", "hi_q": "3D मॉलिक्यूल लैब क्या है?", "hi_a": "यह 3D में रासायनिक संरचनाओं को दिखाता है जो ऑर्गेनिक केमिस्ट्री के लिए बहुत अच्छा है।"},
    {"en_q": "Can I use it on my phone?", "en_a": "Yes. Prepia is 100% mobile-optimized with an app-like feel, bottom sheets, and native-feeling swiping interactions.", "bn_q": "আমি কি ফোনে ব্যবহার করতে পারব?", "bn_a": "হ্যাঁ, এটি ১০০% মোবাইল অপটিমাইজড।", "hi_q": "क्या मैं इसे फोन पर इस्तेमाल कर सकता हूँ?", "hi_a": "हाँ, यह 100% मोबाइल ऑप्टिमाइज़्ड है।"},
    {"en_q": "What is the Neural Feed?", "en_a": "A TikTok-style infinitely scrolling feed of bite-sized educational concepts extracted from your syllabus.", "bn_q": "Neural Feed কী?", "bn_a": "এটি টিকটকের মতো একটি এডুকেশনাল স্ক্রোলিং ফিড।", "hi_q": "न्यूरल फीड क्या है?", "hi_a": "यह टिकटॉक जैसा एक एजुकेशनल स्क्रॉलिंग फीड है।"},
    {"en_q": "Does it support Bengali?", "en_a": "Yes, our AI fully supports Bengali, English, and Hindi. It can extract context in English and teach you in native Bengali.", "bn_q": "এটি কি বাংলা সাপোর্ট করে?", "bn_a": "হ্যাঁ, এটি বাংলা, ইংরেজি এবং হিন্দি সাপোর্ট করে।", "hi_q": "क्या यह बंगाली का समर्थन करता है?", "hi_a": "हाँ, यह बंगाली, अंग्रेजी और हिंदी का समर्थन करता है।"},
    {"en_q": "What is the Concept Battle?", "en_a": "A gamified multiplayer arena where you battle other students or bots in real-time by answering questions from your syllabus.", "bn_q": "Concept Battle কী?", "bn_a": "এটি একটি মাল্টিপ্লেয়ার অ্যারেনা যেখানে আপনি অন্যদের সাথে পড়াশোনার ব্যাটল করতে পারেন।", "hi_q": "कॉन्सेप्ट बैटल क्या है?", "hi_a": "यह एक मल्टीप्लेयर एरिना है जहाँ आप दूसरों के साथ पढ़ाई की लड़ाई कर सकते हैं।"},
    {"en_q": "Are there any hidden costs?", "en_a": "No. The token costs are clearly listed on our Pricing page. No hidden fees.", "bn_q": "এখানে কি লুকানো কোনো খরচ আছে?", "bn_a": "না, সব খরচ প্রাইসিং পেজে পরিষ্কারভাবে লেখা আছে।", "hi_q": "क्या कोई छिपी हुई लागत है?", "hi_a": "नहीं, सभी लागतें मूल्य निर्धारण पृष्ठ पर स्पष्ट रूप से सूचीबद्ध हैं।"},
    {"en_q": "Can I cancel my Pro subscription?", "en_a": "Yes, you can cancel anytime from the Dashboard Settings.", "bn_q": "আমি কি সাবস্ক্রিপশন বাতিল করতে পারব?", "bn_a": "হ্যাঁ, যেকোনো সময় ড্যাশবোর্ড থেকে বাতিল করতে পারবেন।", "hi_q": "क्या मैं सदस्यता रद्द कर सकता हूँ?", "hi_a": "हाँ, आप किसी भी समय डैशबोर्ड से रद्द कर सकते हैं।"},
    {"en_q": "What is the Bionic Reader?", "en_a": "It bolds the first few letters of words, helping neurodivergent students or speed-readers consume text 2x faster.", "bn_q": "Bionic Reader কী?", "bn_a": "এটি শব্দের প্রথম অক্ষরগুলো বোল্ড করে যা ২ গুন দ্রুত পড়তে সাহায্য করে।", "hi_q": "बायोनिक रीडर क्या है?", "hi_a": "यह शब्दों के पहले अक्षरों को बोल्ड करता है जिससे 2x तेजी से पढ़ने में मदद मिलती है।"},
    {"en_q": "How do I earn Karma points?", "en_a": "By helping others on the Bounty Board, completing daily quests, and maintaining your login streak.", "bn_q": "কারমা পয়েন্ট কীভাবে পাবো?", "bn_a": "অন্যদের সাহায্য করে এবং ডেইলি টাস্ক কমপ্লিট করে।", "hi_q": "कर्म बिंदु कैसे प्राप्त करें?", "hi_a": "दूसरों की मदद करके और दैनिक कार्यों को पूरा करके।"},
    {"en_q": "What is the Career Hacker?", "en_a": "An AI that analyzes your skills and generates a step-by-step roadmap for landing jobs in tech.", "bn_q": "Career Hacker কী?", "bn_a": "এটি আপনার দক্ষতা অনুযায়ী জব পাওয়ার গাইডলাইন তৈরি করে।", "hi_q": "करियर हैकर क्या है?", "hi_a": "यह आपके कौशल के आधार पर नौकरी पाने के लिए दिशानिर्देश बनाता है।"},
    {"en_q": "Can I share my notes with friends?", "en_a": "Yes, using the 'Share Context Pack' feature.", "bn_q": "বন্ধুদের সাথে নোট শেয়ার করা যায়?", "bn_a": "হ্যাঁ, শেয়ার কনটেক্সট প্যাক এর মাধ্যমে।", "hi_q": "क्या मैं दोस्तों के साथ नोट्स साझा कर सकता हूँ?", "hi_a": "हाँ, शेयर कॉन्टेक्स्ट पैक के माध्यम से।"},
    {"en_q": "What is Focus Island?", "en_a": "A pomodoro timer mixed with gamification. Keep focusing to grow your island, lose focus and the island dies.", "bn_q": "Focus Island কী?", "bn_a": "এটি একটি গ্যামিফাইড পোমোডোরো টাইমার। ফোকাস করলে আইল্যান্ড বড় হয়।", "hi_q": "फोकस आइलैंड क्या है?", "hi_a": "यह एक गेमीफाइड पोमोडोरो टाइमर है। फोकस करने से आइलैंड बढ़ता है।"},
    {"en_q": "How fast is the AI?", "en_a": "We use edge caching (Upstash Redis) and stream responses. Cache hits are under 20ms, generations are streamed instantly.", "bn_q": "এআই কতটা ফাস্ট?", "bn_a": "খুব ফাস্ট। আমরা ক্যাশিং ব্যবহার করি যাতে ২০ মিলি-সেকেন্ডে রেসপন্স আসে।", "hi_q": "एआई कितना तेज़ है?", "hi_a": "बहुत तेज़। हम कैशिंग का उपयोग करते हैं जिससे 20 मिलीसेकंड में प्रतिक्रिया आती है।"},
    {"en_q": "Can I upload handwritten notes?", "en_a": "Yes, our OCR pipeline handles messy handwritten notes and purifies them into clean digital text.", "bn_q": "হাতের লেখা নোট আপলোড করা যায়?", "bn_a": "হ্যাঁ, আমাদের এআই হাতের লেখাও পড়তে পারে।", "hi_q": "क्या हस्तलिखित नोट्स अपलोड किए जा सकते हैं?", "hi_a": "हाँ, हमारा एआई हस्तलिपि भी पढ़ सकता है।"},
    {"en_q": "What is the Panic Mode?", "en_a": "A viral gamification loop where you must invite 3 friends or pay tokens to unlock a crucial exam survival kit.", "bn_q": "Panic Mode কী?", "bn_a": "পরীক্ষার প্রস্তুতির জন্য একটি স্পেশাল গ্যামিফাইড ফিচার।", "hi_q": "पैनिक मोड क्या है?", "hi_a": "परीक्षा की तैयारी के लिए एक विशेष गेमीफाइड फीचर।"},
    {"en_q": "Is there a student discount?", "en_a": "Our Pro plan is already heavily subsidized for students at just ৳299/month.", "bn_q": "স্টুডেন্ট ডিসকাউন্ট আছে কি?", "bn_a": "স্টুডেন্টদের জন্যই প্রো প্ল্যান মাত্র ২৯৯ টাকায় দেওয়া হচ্ছে।", "hi_q": "क्या कोई छात्र छूट है?", "hi_a": "छात्रों के लिए प्रो प्लान केवल 299 रुपये में दिया जा रहा है।"},
    {"en_q": "What happens to my files if I downgrade?", "en_a": "Free users have a 7-day retention limit. Pro users get permanent storage.", "bn_q": "ডাউনগ্রেড করলে ফাইলের কী হবে?", "bn_a": "ফ্রি ইউজারদের ফাইল ৭ দিন থাকে। প্রো ইউজারদের আজীবন।", "hi_q": "डाउनग्रेड करने पर फाइलों का क्या होगा?", "hi_a": "मुफ़्त उपयोगकर्ताओं की फाइलें 7 दिन रहती हैं। प्रो उपयोगकर्ताओं के लिए आजीवन।"},
    {"en_q": "Can it solve math problems?", "en_a": "Yes, the Pro Academic Solver handles advanced calculus, physics, and LaTeX rendering.", "bn_q": "এটি কি ম্যাথ সলভ করতে পারে?", "bn_a": "হ্যাঁ, প্রো অ্যাকাডেমিক সলভার জটিল অঙ্ক সলভ করতে পারে।", "hi_q": "क्या यह गणित हल कर सकता है?", "hi_a": "हाँ, प्रो एकेडमिक सॉल्वर जटिल गणित हल कर सकता है।"},
    {"en_q": "Do you have an affiliate program?", "en_a": "Yes, invite friends and earn free tokens for both of you.", "bn_q": "অ্যাফিলিয়েট প্রোগ্রাম আছে?", "bn_a": "হ্যাঁ, বন্ধুদের ইনভাইট করে ফ্রি টোকেন পেতে পারেন।", "hi_q": "क्या कोई एफिलिएट प्रोग्राम है?", "hi_a": "हाँ, दोस्तों को आमंत्रित करके मुफ़्त टोकन प्राप्त कर सकते हैं।"},
    {"en_q": "How many files can I upload?", "en_a": "Free users can upload 3 files per week. Pro users have unlimited uploads.", "bn_q": "কয়টি ফাইল আপলোড করা যায়?", "bn_a": "ফ্রি ইউজাররা সপ্তাহে ৩টি। প্রো ইউজাররা আনলিমিটেড।", "hi_q": "कितनी फाइलें अपलोड की जा सकती हैं?", "hi_a": "मुफ़्त उपयोगकर्ता प्रति सप्ताह 3. प्रो उपयोगकर्ता अनलिमिटेड।"},
    
    # 20 NEW FAQS replacing duplicates
    {"en_q": "Is my payment information secure?", "en_a": "Yes, we use Stripe and SSLCommerz for enterprise-grade payment security. We do not store your credit card details on our servers.", "bn_q": "আমার পেমেন্ট ইনফরমেশন কি নিরাপদ?", "bn_a": "হ্যাঁ, আমরা স্ট্রাইপ এবং এসএসএলকমার্স ব্যবহার করি, তাই পেমেন্ট ১০০% নিরাপদ।", "hi_q": "क्या मेरी भुगतान जानकारी सुरक्षित है?", "hi_a": "हाँ, हम स्ट्राइप और एसएसएलकॉमर्स का उपयोग करते हैं, इसलिए भुगतान 100% सुरक्षित है।"},
    {"en_q": "What file types can I upload?", "en_a": "We support PDF, DOCX, TXT, CSV, and common image formats (PNG/JPG) for OCR text extraction.", "bn_q": "কোন ধরনের ফাইল সাপোর্ট করে?", "bn_a": "পিডিএফ, ডকএক্স, টেক্সট এবং ছবি (PNG/JPG) আপলোড করা যায়।", "hi_q": "कौन से फ़ाइल प्रकार समर्थित हैं?", "hi_a": "पीडीएफ, डॉक्स, टेक्स्ट और चित्र (PNG/JPG) अपलोड किए जा सकते हैं।"},
    {"en_q": "Can I use Prepia offline?", "en_a": "Currently, an internet connection is required to communicate with our AI generation servers and load your saved documents.", "bn_q": "প্রেপিয়া অফলাইনে ব্যবহার করা যায়?", "bn_a": "না, এআই চালানোর জন্য ইন্টারনেট কানেকশন প্রয়োজন।", "hi_q": "क्या प्रेपिया को ऑफ़लाइन इस्तेमाल किया जा सकता है?", "hi_a": "नहीं, एआई चलाने के लिए इंटरनेट कनेक्शन आवश्यक है।"},
    {"en_q": "Can I share my Pro account with friends?", "en_a": "Account sharing is strictly monitored to prevent abuse. If you have multiple users, we highly recommend our Family Plans.", "bn_q": "একাউন্ট শেয়ার করা যায়?", "bn_a": "একাউন্ট শেয়ার করা নিষেধ। বন্ধুদের সাথে ব্যবহারের জন্য ফ্যামিলি প্ল্যান নিতে পারেন।", "hi_q": "क्या खाता साझा किया जा सकता है?", "hi_a": "खाता साझा करना प्रतिबंधित है। दोस्तों के साथ उपयोग के लिए फैमिली प्लान लें।"},
    {"en_q": "What is the maximum file size I can upload?", "en_a": "Free users can upload files up to 10MB each. Pro users get an increased limit of 50MB per file.", "bn_q": "ফাইলের ম্যাক্সিমাম সাইজ কত?", "bn_a": "ফ্রি ইউজারদের জন্য ১০এমবি এবং প্রো ইউজারদের জন্য ৫০এমবি।", "hi_q": "फ़ाइल का अधिकतम आकार क्या है?", "hi_a": "मुफ़्त उपयोगकर्ताओं के लिए 10MB और प्रो उपयोगकर्ताओं के लिए 50MB।"},
    {"en_q": "Do you have a refund policy?", "en_a": "Yes, we offer a 7-day money-back guarantee if you have used less than 1000 tokens on your Pro plan.", "bn_q": "রিফান্ড পলিসি আছে কি?", "bn_a": "হ্যাঁ, ৭ দিনের মানি-ব্যাক গ্যারান্টি আছে (শর্ত প্রযোজ্য)।", "hi_q": "क्या कोई रिफंड नीति है?", "hi_a": "हाँ, 7 दिन की मनी-बैक गारंटी है (शर्तें लागू)।"},
    {"en_q": "How accurate are the AI's answers?", "en_a": "Extremely accurate due to our RAG system referencing your exact documents. However, as with all AI, you should double-check critical facts.", "bn_q": "এআই কতটা সঠিক উত্তর দেয়?", "bn_a": "আমাদের RAG সিস্টেমের কারণে এটি খুবই নির্ভুল। তবে গুরুত্বপূর্ণ তথ্যের ক্ষেত্রে নিজে একবার যাচাই করে নেওয়া ভালো।", "hi_q": "एआई कितने सटीक उत्तर देता है?", "hi_a": "हमारे RAG सिस्टम के कारण यह बहुत सटीक है। हालांकि, महत्वपूर्ण जानकारी की पुष्टि करना बेहतर है।"},
    {"en_q": "Can I export my flashcards to Anki?", "en_a": "Yes! You can export any AI-generated flashcard deck as a CSV file to easily import it into Anki or Quizlet.", "bn_q": "ফ্ল্যাশকার্ড আনকি-তে এক্সপোর্ট করা যায়?", "bn_a": "হ্যাঁ, ফ্ল্যাশকার্ড CSV আকারে এক্সপোর্ট করে Anki বা Quizlet এ ইমপোর্ট করতে পারবেন।", "hi_q": "क्या फ्लैशकार्ड अंकी में निर्यात किए जा सकते हैं?", "hi_a": "हाँ, फ्लैशकार्ड को CSV के रूप में निर्यात करके Anki या Quizlet में आयात किया जा सकता है।"},
    {"en_q": "Is there a dark mode?", "en_a": "Prepia was built native dark-mode first for late-night study sessions to protect your eyes.", "bn_q": "ডার্ক মোড আছে?", "bn_a": "প্রেপিয়া পুরোটাই ডার্ক মোডে তৈরি, যাতে রাতে পড়তে সুবিধা হয়।", "hi_q": "क्या डार्क मोड है?", "hi_a": "प्रेपिया पूरी तरह से डार्क मोड में बनाया गया है, ताकि रात में पढ़ने में आसानी हो।"},
    {"en_q": "How do I delete my account?", "en_a": "You can permanently delete your account and all associated data from the 'Danger Zone' in your Dashboard Settings.", "bn_q": "একাউন্ট কীভাবে ডিলিট করবো?", "bn_a": "ড্যাশবোর্ড সেটিংস এর ডেঞ্জার জোন থেকে আপনি চিরতরে একাউন্ট মুছে ফেলতে পারবেন।", "hi_q": "खाता कैसे हटाएं?", "hi_a": "डैशबोर्ड सेटिंग्स के डेंजर जोन से आप स्थायी रूप से खाता हटा सकते हैं।"},
    {"en_q": "Does the AI remember my previous chats?", "en_a": "Yes, full conversation history is securely saved in your database, so the AI maintains context across your sessions.", "bn_q": "এআই কি পূর্বের চ্যাট মনে রাখে?", "bn_a": "হ্যাঁ, আপনার পুরো কনভারসেশন হিস্ট্রি ডাটাবেজে সেভ থাকে।", "hi_q": "क्या एआई पिछली चैट याद रखता है?", "hi_a": "हाँ, आपका पूरा वार्तालाप इतिहास डेटाबेस में सहेजा जाता है।"},
    {"en_q": "What happens if I forget my password?", "en_a": "You can use the 'Forgot Password' link on the login page to receive a secure reset link via email.", "bn_q": "পাসওয়ার্ড ভুলে গেলে কী করবো?", "bn_a": "লগইন পেজে 'ফরগট পাসওয়ার্ড' এ ক্লিক করে রিসেট করতে পারবেন।", "hi_q": "अगर मैं अपना पासवर्ड भूल जाऊं तो क्या करूँ?", "hi_a": "लॉगिन पेज पर 'फॉरगॉट पासवर्ड' पर क्लिक करके रीसेट कर सकते हैं।"},
    {"en_q": "Are there limits on how many questions I can ask?", "en_a": "You are only limited by your available token balance. Pro users get enough tokens for typical heavy usage.", "bn_q": "প্রশ্ন করার কোনো লিমিট আছে?", "bn_a": "আপনার টোকেন ব্যালান্স অনুযায়ী প্রশ্ন করতে পারবেন।", "hi_q": "क्या प्रश्न पूछने की कोई सीमा है?", "hi_a": "आप अपने टोकन बैलेंस के अनुसार प्रश्न पूछ सकते हैं।"},
    {"en_q": "Does it work on tablets and iPads?", "en_a": "Yes, our UI is fully responsive and optimized for touch interactions on iPads and Android tablets.", "bn_q": "এটি কি আইপ্যাড বা ট্যাবলেটে চলে?", "bn_a": "হ্যাঁ, আইপ্যাড ও ট্যাবলেটের জন্য আমাদের সাইট অপ্টিমাইজ করা।", "hi_q": "क्या यह आईपैड या टैबलेट पर काम करता है?", "hi_a": "हाँ, हमारा साइट आईपैड और टैबलेट के लिए अनुकूलित है।"},
    {"en_q": "Can the AI analyze images or diagrams in my PDF?", "en_a": "Yes, our advanced OCR pipeline extracts and interprets diagrams, graphs, and images to provide full context.", "bn_q": "এআই কি ডায়াগ্রাম বুঝতে পারে?", "bn_a": "হ্যাঁ, আমাদের অ্যাডভান্সড ওসিআর ছবির ভেতরের তথ্যও প্রসেস করতে পারে।", "hi_q": "क्या एआई आरेख समझ सकता है?", "hi_a": "हाँ, हमारा उन्नत ओसीआर चित्रों के अंदर की जानकारी को भी प्रोसेस कर सकता है।"},
    {"en_q": "How do I report a bug?", "en_a": "You can report bugs directly through the feedback widget in your dashboard or by emailing our support team.", "bn_q": "বাগ রিপোর্ট করবো কীভাবে?", "bn_a": "ড্যাশবোর্ডের ফিডব্যাক উইজেট বা ইমেইলের মাধ্যমে আমাদের জানাতে পারেন।", "hi_q": "बग रिपोर्ट कैसे करें?", "hi_a": "डैशबोर्ड के फीडबैक विजेट या ईमेल के माध्यम से हमें बता सकते हैं।"},
    {"en_q": "What is the 'Magic Button'?", "en_a": "It's a one-click tool that instantly auto-generates a full study kit (flashcards, quizzes, notes) from your uploaded file.", "bn_q": "ম্যাজিক বাটন কী?", "bn_a": "এটি এক ক্লিকেই একটি ফাইলের ফ্ল্যাশকার্ড, কুইজ ও নোট তৈরি করে দেয়।", "hi_q": "मैजिक बटन क्या है?", "hi_a": "यह एक क्लिक में एक फ़ाइल के फ्लैशकार्ड, क्विज़ और नोट्स बनाता है।"},
    {"en_q": "Can I organize my files into folders?", "en_a": "Yes, you can create 'Context Packs' to group related syllabuses, notes, and slides by subject or semester.", "bn_q": "ফাইল কি ফোল্ডারে রাখা যায়?", "bn_a": "হ্যাঁ, আপনি কনটেক্সট প্যাক বানিয়ে ফাইলগুলো একসাথে রাখতে পারবেন।", "hi_q": "क्या फाइलों को फोल्डर में रखा जा सकता है?", "hi_a": "हाँ, आप कॉन्टेक्स्ट पैक बनाकर फाइलों को एक साथ रख सकते हैं।"},
    {"en_q": "Do you offer enterprise or school licenses?", "en_a": "Yes, we offer bulk licensing and custom deployments for educational institutions. Contact our sales team for details.", "bn_q": "প্রতিষ্ঠানের জন্য কোনো প্যাকেজ আছে?", "bn_a": "হ্যাঁ, স্কুল বা প্রতিষ্ঠানের জন্য আমাদের বাল্ক লাইসেন্স আছে।", "hi_q": "क्या संस्थानों के लिए कोई पैकेज है?", "hi_a": "हाँ, स्कूल या संस्थानों के लिए हमारे पास बल्क लाइसेंस हैं।"},
    {"en_q": "What is the difference between 'Deep Dive' and 'Default' mode?", "en_a": "Deep Dive uses more tokens and a larger context window to provide highly detailed, thesis-level analysis, while Default is optimized for speed.", "bn_q": "ডিপ ডাইভ এবং ডিফল্ট মোডের পার্থক্য কী?", "bn_a": "ডিপ ডাইভ মোডে আরও বিস্তারিত উত্তর পাওয়া যায় যা বড় রিসার্চের জন্য ভালো।", "hi_q": "डीप डाइव और डिफ़ॉल्ट मोड में क्या अंतर है?", "hi_a": "डीप डाइव मोड में अधिक विस्तृत उत्तर मिलते हैं जो बड़े शोध के लिए अच्छा है।"}
]

lines = []
for i, faq in enumerate(faqs):
    idx = i + 1
    # Note: hi_a was mistakenly using hi_q in previous prompt text, fixing here
    lines.append(f"  'faq.{idx}.q': {{ en: \"{faq['en_q']}\", bn: \"{faq['bn_q']}\", hi: \"{faq['hi_q']}\" }},")
    lines.append(f"  'faq.{idx}.a': {{ en: \"{faq['en_a']}\", bn: \"{faq['bn_a']}\", hi: \"{faq['hi_a']}\" }},")

injection = "\n".join(lines)

if "};" in content:
    content = content.replace("};", ",\n" + injection + "\n};")

with open('frontend/src/app/landingTranslations.ts', 'w', encoding='utf-8') as f:
    f.write(content)

print("landingTranslations.ts updated with 50 FAQs!")
